'use strict';

/**
 * Domain & Telemetry Event Types for ShilpSetu.
 */
const EventTypes = {
  // User Authentication & Identity
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',

  // Product Lifecycle & Interaction
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_VIEWED: 'PRODUCT_VIEWED',
  PRODUCT_SAVED: 'PRODUCT_SAVED',
  PRODUCT_PUBLISHED: 'PRODUCT_PUBLISHED',
  PRODUCT_REJECTED: 'PRODUCT_REJECTED',
  PRODUCT_FEATURED: 'PRODUCT_FEATURED',

  // Commerce & Cart
  CART_ADDED: 'CART_ADDED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_COMPLETED: 'ORDER_COMPLETED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  PAYMENT_UPDATED: 'PAYMENT_UPDATED',

  // AI & Intelligence
  AI_CATALOG_GENERATED: 'AI_CATALOG_GENERATED',
  PRICE_ANALYZED: 'PRICE_ANALYZED',

  // Artisan Verification
  ARTISAN_VERIFIED: 'ARTISAN_VERIFIED',
  ARTISAN_REJECTED: 'ARTISAN_REJECTED',
  ARTISAN_SUSPENDED: 'ARTISAN_SUSPENDED',

  // Communication
  INQUIRY_RECEIVED: 'INQUIRY_RECEIVED',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
};

module.exports = EventTypes;
