'use strict';

const https = require('https');
const { env } = require('../../config/env');
const logger = require('../../utils/logger');

/**
 * Gemini Catalog Provider — Generates AI craft stories, descriptions,
 * multilingual translations, and structured product attributes using Google Gemini REST API.
 */
class GeminiCatalogProvider {
  constructor() {
    this.name = 'gemini';
  }

  isAvailable() {
    return Boolean(env.GEMINI_API_KEY && (env.CATALOG_PROVIDER === 'gemini' || env.CATALOG_PROVIDER === 'default'));
  }

  /**
   * Helper to make HTTP POST requests to Gemini API.
   */
  async _callGemini(prompt, systemInstruction = '', inlineImages = []) {
    if (!this.isAvailable()) {
      return {
        status: 'provider_unavailable',
        error: 'Gemini AI provider is not configured. Set GEMINI_API_KEY and CATALOG_PROVIDER=gemini in environment.',
      };
    }

    const model = env.GEMINI_MODEL || 'gemini-1.5-flash';
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(env.GEMINI_API_KEY)}`;

    const parts = [];

    // Add inline images if provided
    for (const img of inlineImages) {
      if (img.buffer && img.mimeType) {
        parts.push({
          inlineData: {
            mimeType: img.mimeType,
            data: img.buffer.toString('base64'),
          },
        });
      }
    }

    // Add prompt text
    parts.push({ text: prompt });

    const payload = {
      contents: [
        {
          role: 'user',
          parts: parts,
        },
      ],
      generationConfig: {
        temperature: 0.4,
        topP: 0.95,
        maxOutputTokens: 2048,
        responseMimeType: 'application/json',
      },
    };

    if (systemInstruction) {
      payload.systemInstruction = {
        parts: [{ text: systemInstruction }],
      };
    }

    const requestBody = JSON.stringify(payload);
    const url = new URL(endpoint);

    return new Promise((resolve) => {
      const req = https.request(
        {
          hostname: url.hostname,
          path: `${url.pathname}${url.search}`,
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(requestBody),
          },
        },
        (res) => {
          let rawData = '';
          res.on('data', (chunk) => {
            rawData += chunk;
          });

          res.on('end', () => {
            try {
              const data = JSON.parse(rawData);

              if (res.statusCode >= 400 || data.error) {
                const errMsg = data.error?.message || `Gemini API error ${res.statusCode}`;
                logger.error(`Gemini API error: ${errMsg}`);
                return resolve({
                  status: 'failed',
                  error: errMsg,
                });
              }

              const candidate = data.candidates?.[0];
              const textContent = candidate?.content?.parts?.[0]?.text;

              if (!textContent) {
                return resolve({
                  status: 'failed',
                  error: 'No content generated by AI model',
                });
              }

              // Parse JSON response
              let parsedResult;
              try {
                // Remove markdown code fences if present
                const cleaned = textContent.replace(/```(?:json)?\n?/g, '').trim();
                parsedResult = JSON.parse(cleaned);
              } catch (parseErr) {
                logger.warn(`Failed to parse Gemini response as JSON: ${parseErr.message}`);
                parsedResult = { rawText: textContent };
              }

              return resolve({
                status: 'completed',
                data: parsedResult,
                finishReason: candidate.finishReason,
              });
            } catch (err) {
              logger.error(`Failed to process Gemini response: ${err.message}`);
              return resolve({
                status: 'failed',
                error: 'Invalid response from AI provider',
              });
            }
          });
        }
      );

      req.on('error', (err) => {
        logger.error(`Gemini request error: ${err.message}`);
        resolve({
          status: 'failed',
          error: `Network error connecting to AI service: ${err.message}`,
        });
      });

      req.write(requestBody);
      req.end();
    });
  }

  /**
   * Generate complete catalog content from artisan product details and optional image.
   */
  async generateCatalog(input, imageBuffer = null, mimeType = null) {
    const systemInstruction = `You are ShilpSetu's master artisan storyteller and e-commerce specialist for authentic Indian handicrafts and handlooms.
Generate rich, accurate, respectful, and appealing e-commerce catalog content for an artisan's handmade product.
All content must emphasize heritage, cultural significance, craft technique, materials, care instructions, and SEO optimization.
Respond ONLY with a valid JSON object matching the requested schema.`;

    const prompt = `Product Information:
Title / Craft Name: ${input.craftName || input.title || 'Handmade Craft'}
Artisan Name: ${input.artisanName || 'Traditional Indian Artisan'}
Region / State: ${input.region || input.state || 'India'}
Craft Category: ${input.category || 'Handicrafts'}
Raw Materials: ${Array.isArray(input.materials) ? input.materials.join(', ') : input.materials || 'Natural materials'}
Technique / Method: ${input.technique || 'Handmade traditional technique'}
Time taken to create: ${input.hoursToMake ? `${input.hoursToMake} hours` : input.duration || 'Several days'}
Keywords / Notes: ${input.notes || input.rawDescription || 'Authentic handmade heritage item'}
Requested Output Languages: ${Array.isArray(input.languages) ? input.languages.join(', ') : 'English, Hindi, Gujarati'}

Generate a JSON object with this exact structure:
{
  "title": "SEO-friendly, evocative title for the product",
  "shortDescription": "2-3 sentence punchy summary highlighting handmade nature and heritage",
  "longDescription": "Detailed 2-3 paragraph description covering history, visual appeal, utility, and uniqueness",
  "craftStory": "Emotive story about the artisan, heritage tradition, and time-honored craft technique",
  "culturalSignificance": "1-2 paragraphs detailing the cultural, historical, or geographical importance (e.g., GI tag context if applicable)",
  "features": ["bullet point 1", "bullet point 2", "bullet point 3", "bullet point 4"],
  "materials": ["list of pure materials used"],
  "careInstructions": ["step by step care instructions to preserve the handmade item"],
  "dimensionsRecommendation": "Suggested dimension format (e.g., Height x Width x Weight)",
  "seoKeywords": ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6"],
  "suggestedCategories": ["primary category", "secondary sub-category"],
  "multilingual": {
    "hi": {
      "title": "Hindi title",
      "shortDescription": "Hindi short description",
      "craftStory": "Hindi craft story"
    },
    "gu": {
      "title": "Gujarati title",
      "shortDescription": "Gujarati short description",
      "craftStory": "Gujarati craft story"
    }
  }
}`;

    const images = imageBuffer && mimeType ? [{ buffer: imageBuffer, mimeType }] : [];
    return this._callGemini(prompt, systemInstruction, images);
  }

  /**
   * Translate text content into requested Indian languages.
   */
  async translateContent(content, targetLanguages = ['hi', 'gu', 'en']) {
    const systemInstruction = `You are an expert translator specializing in Indian languages (Hindi, Gujarati, Tamil, Bengali, Marathi, Telugu, Kannada, etc.) and handicraft terminology.
Translate the given product catalog text accurately, maintaining cultural nuance and artisan dignity.
Respond ONLY with a JSON object mapping language codes to translated fields.`;

    const prompt = `Translate the following handicraft product content into target languages: [${targetLanguages.join(', ')}].

Source Content:
Title: ${content.title || ''}
Short Description: ${content.shortDescription || ''}
Craft Story: ${content.craftStory || ''}
Care Instructions: ${Array.isArray(content.careInstructions) ? content.careInstructions.join('; ') : content.careInstructions || ''}

Return JSON formatted as:
{
  "translations": {
    "<langCode>": {
      "title": "...",
      "shortDescription": "...",
      "craftStory": "...",
      "careInstructions": ["..."]
    }
  }
}`;

    return this._callGemini(prompt, systemInstruction);
  }
}

module.exports = new GeminiCatalogProvider();
